app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('error', function(){
    abort(500);
});
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::auth();

Route::get('home', 'HomeController@index');
Route::get('subnotas', function(){

	return view('notas');
});

/*Controlador nota de entrega*/
Route::resource('notasEntregas', 'notas_entregaController');
Route::get('anularNotae/{id}', 'notas_entregaController@anular');
Route::get('reporteNotae', 'notas_entregaController@reportes')->name('reporteNotae');





Route::resource('facturas', 'facturaController');
Route::get('anularFactura/{id}', 'facturaController@anular');
Route::get('reporteFactura', 'facturaController@reportes')->name('reporteFactura');


Route::resource('clientes', 'clientesController');
Route::resource('users', 'UserController');

Route::resource('vendedors', 'vendedorController');
Route::resource('products', 'ProductController');
Route::resource('inventarios', 'inventarioController');

/*Carga y descarga de inventario*/

Route::get('inventarioCarga/{id}', 'inventarioController@upload')->name('inventarios.upload');
Route::get('inventarioDescarga/{id}', 'inventarioController@download')->name('inventarios.download');
Route::post('inventarioCargaPost', 'inventarioController@upload_post')->name('inventarios.upload_post');
Route::resource('configuracions', 'configuracionController');



/*Controlador para seleccion de empresa*/
Route::get('notasEntregas/infoCliente/{id}', 'clientesController@infoCliente');
Route::get('facturas/infoCliente/{id}', 'clientesController@infoCliente');

/*Controlador para devolver informacion de inventario*/
Route::get('facturas/infoInventario/{id}', 'facturaController@infoInventario');


Route::get('impresoraPdf/{id_nota}', 'pdfController@notaEntrega');
Route::get('impresoraPdffactura/{id_factura}', 'pdfController@factura');

app/Http/Controllers/reporteController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests;
use DB;
/*modelos*/

use App\Models\clientes;
use App\Models\notas_entrega;
use App\Models\items_notas_entregas;

use App\Models\notas_debito;
use App\Models\items_notas_debito;
use App\Models\notas_credito;
use App\Models\items_notas_credito;

use App\Models\factura;
use App\Models\items_factura;

use App\Models\configuracion;



class reporteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    	$notas_entrega= DB::table('notas_entregas')
    	->join('clientes', 'clientes.id', '=', 'notas_entregas.empresa_nombre')
    	->whereNull('notas_entregas.deleted_at')
      ->select('notas_entregas.*', 'nombre_razon_social')
      ->paginate(60);

    	$clientes= clientes::all(['id', 'nombre_razon_social']);



      $facturas = DB::table('facturas')
    	->join('clientes', 'clientes.id', '=', 'facturas.clientes_id')
          ->whereNull('facturas.deleted_at')
      ->select('facturas.*', 'nombre_razon_social', 'nota_codigo')
    	->paginate(60);
      dd($facturas);
      //$facturas->setPath('reportes%123tab_4');


        return view ('reportes.index')->with('clientes', $clientes)->with('notas_entrega', $notas_entrega)->with('notas_debito', $notas_debito)->with('notas_credito', $notas_credito)->with('facturas', $facturas);
    }


}

resources/views/reportes/index.blade.php
@extends('layouts.admin')

@section('content')

  @include('flash::message')


  <div class="col-md-12">
    <!-- Custom Tabs -->
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true"> <span> <strong> NOTAS DE ENTREGA  </strong></span></a></li>
        <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false"> <span> <strong> NOTAS DE DÉBITO  </strong></span></a></li>
        <li><a href="#tab_3" data-toggle="tab"> <span> <strong> NOTAS DE CRÉDITO  </strong></span></a></li>
        <li><a href="#tab_4" data-toggle="tab"> <span> <strong> FACTURAS </strong></span></a></li>

        <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
          <div class="box">
            <div class="box-header">



            </div>



            <div class="box-body table-responsive no-padding">
              <table id="example1" class="table table-bordered table-hover dataTable" role="grid">
                <thead>
                  <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">CODÍGO NOTA</th>
                    <th>
                      ESTATUS
                    </th>
                    <th>EMPRESA</th>
                    <th>RIF/CI</th>
                    <th>FECHA EMISIÓN</th>
                    <th>ACCIONES</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($notas_entrega as $nota)
                    <tr>
                      <td><strong>{{$nota->nota_codigo}}</strong></td>
                      <td>
                        @if($nota->estatus==1)
                          <span class="label label-success">ACTIVA</span>
                        @else
                          <span class="label label-warning"> ANULADA </span>
                        @endif
                      </td>
                      <td>{{$nota->nombre_razon_social}}</td>
                      <td>{{$nota->ci_rif}}</td>
                      <td>
                        <?php echo \Carbon\Carbon::createFromFormat('Y-m-d', $nota->fecha_emision)->formatLocalized('%d %b %Y'); ?>
                      </td>
                      <td>
                        {!! Form::open(['route' => ['notasEntregas.destroy', $nota->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                          <a href="impresoraPdf/{{$nota->id}}" target="_blank" class='btn btn-default btn-sm'><i class="fa fa-print" aria-hidden="true"></i></a>
                          <a href="{!! route('notasEntregas.edit', [$nota->id]) !!}" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-edit"></i></a>
                          <a href="anularNotae/{{$nota->id}}" class='btn btn-warning btn-sm' onclick="return confirm('¿Desea anular el registro seleccionado ?')"><i class="fa fa-ban" aria-hidden="true"></i></a>

                          {!! Form::button('<i class="fa fa-trash-o"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('¿Desea eliminar el registro seleccionado ?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
              <div class="col-xs-12">
                Página {{$notas_entrega->currentPage()}}  de {{ $notas_entrega->lastPage()}}
                <ul class="pagination hidden-xs pull-right">
                  {{ $notas_entrega->links() }}
                </ul>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.tab-pane -->
        <div class="tab-pane" id="tab_2">
          <div class="box">
            <div class="box-header">




            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table id="example2" class="table table-bordered table-hover dataTable" role="grid">
                <thead>
                  <th>CODÍGO NOTA</th>
                  <th>
                    ESTATUS
                  </th>
                  <th>EMPRESA</th>
                  <th>RIF/CI</th>
                  <th>FECHA EMISIÓN</th>
                  <th>ACCIONES</th>
                </thead>
                <tbody>
                  @foreach($notas_debito as $nota_debito)
                    <tr>
                      <td><strong>{{$nota_debito->nota_debito_codigo}}</strong></td>
                      <td>
                        @if($nota_debito->estatus==1)
                          <span class="label label-success">ACTIVA</span>
                        @else
                          <span class="label label-warning"> ANULADA </span>
                        @endif

                      </td>
                      <td>{{$nota_debito->nombre_razon_social}}</td>
                      <td>{{$nota_debito->ci_rif}}</td>
                      <td>
                          <?php echo \Carbon\Carbon::createFromFormat('Y-m-d', $nota_debito->fecha_emision)->formatLocalized('%d %b %Y'); ?>
                      </td>
                      <td>
                        {!! Form::open(['route' => ['notasDebitos.destroy', $nota_debito->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                          <a href="impresoraPdfnota/{{$nota_debito->id}}" target="_blank" class='btn btn-default btn-sm'><i class="fa fa-print" aria-hidden="true"></i></a>
                          <a href="anularNotad/{{$nota_debito->id}}" class='btn btn-warning btn-sm' onclick="return confirm('¿Desea anular el registro seleccionado ?')"><i class="fa fa-ban" aria-hidden="true"></i></a>
                          {!! Form::button('<i class="fa fa-trash-o"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('¿Desea eliminar el registro seleccionado ?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
              <div class="col-xs-12">
                Página {{$notas_debito->currentPage()}}  de {{ $notas_debito->lastPage()}}
                <ul class="pagination hidden-xs pull-right">
                  {{ $notas_debito->links() }}
                </ul>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.tab-pane -->
        <div class="tab-pane" id="tab_3">
          <div class="box">
            <div class="box-header">


            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table id="example3" class="table table-bordered table-hover dataTable" role="grid">
                <thead>
                  <th>CODÍGO NOTA</th>
                  <th>
                    ESTATUS
                  </th>
                  <th>EMPRESA</th>
                  <th>RIF/CI</th>
                  <th>FECHA EMISIÓN</th>
                  <th>ACCIONES</th>
                </thead>
                <tbody>
                  @foreach($notas_credito as $nota_credito)
                    <tr>
                      <td><strong>{{$nota_credito->nota_credito_codigo}}</strong></td>
                      <td>
                        @if($nota_credito->estatus==1)
                          <span class="label label-success">ACTIVA</span>
                        @else
                          <span class="label label-warning"> ANULADA </span>
                        @endif
                      </td>
                      <td>{{$nota_credito->nombre_razon_social}}</td>
                      <td>{{$nota_credito->ci_rif}}</td>
                      <td>
                        <?php echo \Carbon\Carbon::createFromFormat('Y-m-d', $nota_credito->fecha_emision)->formatLocalized('%d %b %Y'); ?>
                      </td>
                      <td>
                        {!! Form::open(['route' => ['notasCreditos.destroy', $nota_credito->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                          <a href="impresoraPdfnotac/{{$nota_credito->id}}" target="_blank" class='btn btn-default btn-sm'><i class="fa fa-print" aria-hidden="true"></i></a>
                          <a href="anularNotac/{{$nota_credito->id}}" class='btn btn-warning btn-sm' onclick="return confirm('¿Desea anular el registro seleccionado ?')"><i class="fa fa-ban" aria-hidden="true" ></i></a>

                          {!! Form::button('<i class="fa fa-trash-o"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('¿Desea eliminar el registro seleccionado ?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
              <div class="col-xs-12">
                Página {{$notas_credito->currentPage()}}  de {{ $notas_credito->lastPage()}}
                <ul class="pagination hidden-xs pull-right">
                  {{ $notas_credito->links() }}
                </ul>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.tab-pane -->


        <!-- /.tab-pane -->
        <div class="tab-pane" id="tab_4">
          <div class="box">
            <div class="box-header">


            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table id="example4" class="table table-bordered table-hover dataTable" role="grid">
                <thead>
                  <th>CODÍGO FACTURA</th>
                  <th>
                    ESTATUS
                  </th>
                  <th>EMPRESA</th>
                  <th>RIF/CI</th>
                  <th>
                    NOTA DE ENTREGA
                  </th>
                  <th>FECHA EMISIÓN</th>
                  <th>ACCIONES</th>
                </thead>
                <tbody>
                  @foreach($facturas as $factura)
                    <tr>
                      <td><strong>{{$factura->factura_codigo}}</strong></td>
                      <td>
                        @if($factura->estatus==1)
                          <span class="label label-success">ACTIVA</span>
                        @else
                          <span class="label label-warning"> ANULADA </span>
                        @endif
                      </td>
                      <td>{{$factura->nombre_razon_social}}</td>
                      <td>{{$factura->ci_rif}}</td>
                      <td>
                        @if($factura->nota_codigo=="")
                            <span class="label label-warning">Sin nota de entrega</span>
                        @else
                            <span class="label label-danger">{{$factura->nota_codigo}}</span>
                        @endif

                      </td>
                      <td>
                          <?php echo \Carbon\Carbon::createFromFormat('Y-m-d', $factura->fecha_emision)->formatLocalized('%d %b %Y'); ?>
                      </td>
                      <td>
                        {!! Form::open(['route' => ['facturas.destroy', $factura->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                          <a href="impresoraPdffactura/{{$factura->id}}" target="_blank" class='btn btn-default btn-sm'><i class="fa fa-print" aria-hidden="true"></i></a>
                          <a href="{!! route('facturas.edit', [$factura->id]) !!}" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-edit"></i></a>
                          <a href="anularFactura/{{$factura->id}}" class='btn btn-warning btn-sm' onclick="return confirm('¿Desea anular el registro seleccionado ?')"><i class="fa fa-ban" aria-hidden="true"></i></a>

                          {!! Form::button('<i class="fa fa-trash-o"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm', 'onclick' => "return confirm('¿Desea eliminar el registro seleccionado ?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
              <div class="col-xs-12">
                {{-- Página {{$facturas->currentPage()}}  de {{ $facturas->lastPage()}}
                 --}}<ul class="pagination hidden-xs pull-right">
                  {{ $facturas->links()
                       
                    }}

                </ul>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
    </div>
    <!-- nav-tabs-custom -->
  </div>
@endsection